### ISSUE TITLE
External monitor doesn't work

### ISSUE THREAD

**Issue by UserXGnu** [archcraft-os/archcraft-hyprland#1]
Hi, I noticed when running with bumblebee or without it (DRM modesetting enabled) with Intel+nvidia, it runs, but no external monitor is recognized. I don't really know how to tackle this one. So, maybe you have an idea....

**Comment by adi1090x** [comment]
Well, Have you tried putting your monitor configs in file: `~/.config/hypr/hyprland.conf`
Check the example there on line 10

**Comment by adi1090x** [comment]
Edit `~/.config/hypr/hyprland.conf` file and modify output setting at line 150.
