### ISSUE TITLE
Error setting value for <dwindle:col.group_border_active>: no such field

### ISSUE THREAD

**Issue by EduardoHM98** [archcraft-os/archcraft-hyprland#13]
Installed hyprland on Arch after using GNOME for a while.
[screenshot](https://imgur.com/uxbkGBm)

**Comment by EduardoHM98** [comment]
Fixed by moving 'col.group_border_active' and 'col.group_border' to the 'general' section of the config file as per [the wiki](https://wiki.hyprland.org/Configuring/Variables/).

**Comment by adi1090x** [comment]
Updated!
