### ISSUE TITLE
after install follow the intruction i can't login to hyprland

### ISSUE THREAD

**Issue by seyhadot** [archcraft-os/archcraft-hyprland#14]

**Comment by yusiwen** [comment]
Same issue here! Anyone can help? thanks

**Comment by abadawe-dev** [comment]
It is an issue with NVIDIA drivers, it is possible to resolve as I have run hyprland with NVIDIA drivers before using [SolDoesTech's](https://github.com/SolDoesTech) install script [HyprV4](https://github.com/SolDoesTech/HyprV4) and it seems like other people like [JaKooLit](https://github.com/JaKooLit) have it working with their [Hyprland-v3](https://github.com/JaKooLit/Hyprland-v3) install script, I have linked these files in case someone can figure out the differences between their implementations and archcraft's one and fix archcraft-hyprland on proprietary NVIDIA drivers.

THIS ONLY WORKS IF YOU HAVE AN IGPU(?)

In the mean time, just install an opensource driver using `sudo pacman -S xf86-video-vesa` then uninstall the NVIDIA  drivers, you can list all of them using `sudo pacman -Q | grep "nvidia"`, then remove the packages one by one listed using `pacman -Rns package-name`. Reboot and you should be able to login into hyprland. Credits to u/weltonvs on the r/archacraft subreddit for this fix.

I hope @adi1090x properly fixes this properly as a product he charges for should never be this finicky to get working.

**Comment by adi1090x** [comment]
I'll work on that soon, thanks for the head-ups.

**Comment by adi1090x** [comment]
Just Updated the config with better Nvidia support, try again and let me know.
