### ISSUE TITLE
Hyprland config issue

### ISSUE THREAD

**Issue by smvassallo74** [archcraft-os/archcraft-hyprland#18]
Hi,

I purchased the Hyprland configuration which does not load the desktop.

I originally thought it was a screen resolution issue but it is not.

I get the following error in the swaylock.log

2023-07-15 10:28:14 - [swaylock-1.7.2/main.c:1211] Parsing CLI Args
2023-07-15 10:28:14 - [swaylock-1.7.2/main.c:1242] Unable to connect to the compositor. If your compositor is running, check or set the WAYLAND_DISPLAY environment variable.
2023-07-15 10:28:14 - [swaylock-1.7.2/pam.c:88] Prepared to authorize user simon

I am running the latest Archcraft build.

**Comment by adi1090x** [comment]
Nvidia?

**Comment by smvassallo74** [comment]
No Intel. 

00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 0b) (prog-if 00 [VGA controller])
        Subsystem: Lenovo Haswell-ULT Integrated Graphics Controller
        Flags: bus master, fast devsel, latency 0, IRQ 45
        Memory at e0000000 (64-bit, non-prefetchable) [size=4M]
        Memory at c0000000 (64-bit, prefetchable) [size=512M]
        I/O ports at 3000 [size=64]
        Expansion ROM at 000c0000 [virtual] [disabled] [size=128K]
        Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
        Capabilities: [d0] Power Management version 2
        Capabilities: [a4] PCI Advanced Features
        Kernel driver in use: i915
        Kernel modules: i915

**Comment by adi1090x** [comment]
Just Updated the config, try again and let me know.

**Comment by smvassallo74** [comment]
Still the same issue.
