### ISSUE TITLE
Layouts

### ISSUE THREAD

**Issue by UserXGnu** [archcraft-os/archcraft-hyprland#2]
Hi, I noticed this video on redit and I was wondering...how do I get those layouts to work here?

https://www.reddit.com/r/unixporn/comments/vdl8rj/hyprland_hyprland_20_full_video_in_comment/

Rightnow, with your current build, it only has dwindle and float

BR \

**Comment by adi1090x** [comment]
Yes, that's the only layout we have. and these are the same layout in my videos as well. Just open windows, move them arround and  you'll get the same result as in video.
