### ISSUE TITLE
waybar-wlr-workspaces does not load

### ISSUE THREAD

**Issue by ghost** [archcraft-os/archcraft-hyprland#22]
Module wlr/workspaces in waybar does not load. To fix, you need to rename wlr/workspaces to hyprland/workspaces in both ~/.config/hypr/waybar/config and ~/.config/hypr/waybar/modules.

See here: https://github.com/Alexays/Waybar/wiki/Module:-Workspaces

**Comment by adi1090x** [comment]
Fixed! Update the configs. Released today.
