### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by danilo-lopes** [archcraft-os/archcraft-hyprland#24]
Please, improve the documentation. I installed Arch Linux and copy paste as described on README and I got:

- Fonts broken
- Didn't understand how to install themes, icons, cursor themes and fonts

**Comment by ghost** [comment]
Agreed that this is a slight issue, I tried installing this on base arch and didn't know what to do as well at first. The reason why it doesn't work is that it uses the Archcraft repo from when you install Archcraft for the fonts and themes, which are not available in the standard repos.

At that point, you really only have 2 options: 
1. Modify some of the configs to match with custom theming, like in the case of Catppuccin you could install the [Catppuccin GTK theme](https://aur.archlinux.org/packages/catppuccin-gtk-theme-mocha) from the AUR, and I'm sure things like the cursor themes and icons you could also install as well. After that, you'll need to change the configs to work with the other packages.
2. Install the needed Archcraft packages from [here](https://github.com/archcraft-os/pkgs/tree/main/x86_64) and then install them to any other Arch Linux distribution with `sudo pacman -U 'package name'`. Downside is you don't have automatic updates. (Unless someone knows to add the Archcraft repo outside Archcraft, but I do not)

It is really complicated, but I do understand why it does not work properly, hopefully this helps you.

**Comment by adi1090x** [comment]
Well the documentation are pretty straightforward, If you're on Archcraft, Only then install the provided packages. If you're on any other distro, then follow the instructions which are very simple, install all the required programs, put the config files in their respective locations, install the fonts, themes and icons which are provided in the tar file to their expected locations. 

Anyway, I'll try to improve the docs further.
