### ISSUE TITLE
A bug and small annoyances

### ISSUE THREAD

**Issue by M1n-74316D65** [archcraft-os/archcraft-hyprland#7]
Hi, first of all amazing work.

- (Bug) I installed the non Catppuccin version and then installed the Catppuccin version, this resulted on the top text being white.
- (Annoyance) I don't know if the default resolution is intended, but if it's, you should put in the README how to change it.
- (Annoyance) I don't know either if the small font on the console is intended, maybe you should put how to increase it on the README too.

![imagen](https://user-images.githubusercontent.com/54779580/203666408-323cb038-ef77-4d53-aa1e-577b73c182e1.png)

**Comment by adi1090x** [comment]
Update the configs.
