### ISSUE TITLE
How to set themes, icons, etc? 

### ISSUE THREAD

**Issue by brymon68** [archcraft-os/archcraft-hyprland#8]
Hello,

I see that themes are referenced in the wiki but there are no docs for how to install the theme? Placing the gtk/theme/ directory into ~/.themes/ directory did not work for me. Is this set through an ENV? 

I have the same question for Icons. How do we setup icons?

**Comment by adi1090x** [comment]
Edit `~/.config/hypr/scripts/gtkthemes` script.
