### ISSUE TITLE
is it possible to create such a theme for hyprland?

### ISSUE THREAD

**Issue by Wjxfi** [archcraft-os/archcraft-hyprland#9]
more optimized, improved

now it spends 700mb on one window and installation bugs

But you can make it better than ever and then it will make sense to go to hyprland (now your premiums are better than regular hyprland)

But this design theme will change everything (for me)

She's really beautiful:
https://youtu.be/fbTBhCGZBOQ
(https://github.com/Selmer443/dotfiles)

just add it to be able to include

**Comment by adi1090x** [comment]
You can easily replicate that by editing files like `~/.config/hypr/waybar` and `~/.config/hypr/foot`. Put the wallpapers in `~/.config/hypr/wallpapers`

In future, I'll add multiple themes.
